### ISSUE TITLE
Zoom is not working

### ISSUE THREAD

**Issue by mvala** [mvala/jsroot-example#4]
@linev, i just checked project and start clean install and i cannot zoom in historgam and i don't see menu when i right click on histogram also

**Comment by linev** [comment]
Can you check here:

http://jsroot.gsi.de/dev/examples.htm#th2_colz

It is copy of code from repository.
Most probably, you should clean your browser cache

**Comment by mvala** [comment]
Your example is not working, too. Even after cleaning cache. Yesterday i had firefox (45.0) update. May this be cause of it?

**Comment by linev** [comment]
Very strange.
I also using Firefox 45.0. 
Have no problem.

I using following plugin:
https://addons.mozilla.org/en-us/firefox/addon/empty-cache-button/
Simple reload not helps.

**Comment by mvala** [comment]
Nope, it didn't help

**Comment by linev** [comment]
Could you try Chrome (I also use it in my testing) or IE?

**Comment by linev** [comment]
Are you testing jsroot-example or this link 

http://jsroot.gsi.de/dev/examples.htm#th2_colz

**Comment by mvala** [comment]
chrome is working. Always trying this link. So it is problem on my firefox.

**Comment by mvala** [comment]
Here is output in my firefox console

```
"Set JSROOT.source_dir to http://jsroot.gsi.de/dev/, dev 14/03/2016" JSRootCore.js:126:13
"loading http://jsroot.gsi.de/dev/scripts/rawinflate.js ..." JSRootCore.js:206:10
"loading http://jsroot.gsi.de/dev/scripts/JSRootIOEvolution.js ..." JSRootCore.js:206:10
"loading http://jsroot.gsi.de/dev/scripts/d3.v3.min.js ..." JSRootCore.js:206:10
"loading http://jsroot.gsi.de/dev/scripts/JSRootPainter.js ..." JSRootCore.js:206:10
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.v3.min.js:3:10389
zaxis path 109 JSRootPainter.js:3512:7
xaxis path 409 JSRootPainter.js:3512:7
yaxis path 451 JSRootPainter.js:3512:7
zaxis path 109
```

**Comment by linev** [comment]
> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.v3.min.js:3:10389

Never saw such kind of errors.
If you will not find problem, one should switch to normal (not minimized) version of d3.js to see there it comes from.

**Comment by mvala** [comment]
```
    object.__proto__ = prototype;
```

it is in line 553 in my case

**Comment by linev** [comment]
Without Firebug I also see this warning - but it still works for me.

**Comment by mvala** [comment]
maybe problem si that fedora 23 did some extra patch

**Comment by linev** [comment]
I will check tomorrow.
In any case I would like to understand why this warning appears.

**Comment by mvala** [comment]
this is what i found
http://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance

**Comment by linev** [comment]
Just for curiosity. 
Please check last release version:
http://jsroot.gsi.de/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz
and this:
http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz&tooltip=1

New tooltip functionality could have side effect like you observe

**Comment by mvala** [comment]
both links don't work (i mean zoom)

**Comment by linev** [comment]
Dear Martin,

Please try once again:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz

I changed little bit zooming implementation. Probably, it could help.
If not, we will need to add a lot of debug messages to see where it fails.

**Comment by mvala** [comment]
no it is not working. I downgraded to firefox 41 and everything is working there. I use google-chorme and it is working also. only firefox 45.0 on my fedora workstation is problem

**Comment by linev** [comment]
> only firefox 45.0 on my fedora workstation is problem

Lets try again. I add log output in mouse events handling.
You should see in console when you try to zoom two messages:
   start rect sel 0
   first move of rect sel 1

**Comment by mvala** [comment]
I see only

```
"Set JSROOT.source_dir to http://jsroot.gsi.de/dev/, dev 16/03/2016" JSRootCore.min.js:1:2684
zaxis path 118 JSRootPainter.min.js:1:76905
xaxis path 409 JSRootPainter.min.js:1:76905
yaxis path 451 JSRootPainter.min.js:1:76905
zaxis path 118
```

**Comment by mvala** [comment]
Basically i cannot see menu when i right click. If you want i can share my screen and we can debug it together

**Comment by linev** [comment]
That means that your Firefox does not react on mouse events.
Because first message "start rect sel 0" should appear always when you click with mouse on the frame.
I have no idea that could be wrong with your Firefox.

**Comment by mvala** [comment]
i will report bug and we will see, what they say. So Can you formulate for me, what should i write as bug report?

**Comment by linev** [comment]
Before we submit error report, we should try more simple examples.
Probably I create such example, where problem should be reproduced.
It also would be nice if you can give me vnc connection to your machine, that I check several ideas myself.

**Comment by linev** [comment]
Please try this simple example:

https://jsfiddle.net/zu1eks5q/

It repeats logic how events handled in jsroot.
Try to go with mouse over rect, press mouse button, make double click.
All such events should be visible and displayed in text box

**Comment by mvala** [comment]
All events work, but only right click doesn't

**Comment by mvala** [comment]
And left-click and drag doesn't work also

**Comment by linev** [comment]
As you can see from the source code, I only implement mousedown and dblclick events.
Rest are ignored at the moment. Are you see both of these events?

**Comment by mvala** [comment]
All events in source code are wroking. Can you add draging (which is when you zoom y axis for example) and rightclick

**Comment by linev** [comment]
In fact, in JSROOT we do not see already these two events - mousedown and dblclick. 
Means something else play a role here.
I have several conditions in the code, which could prevent to assign events handlers. Like this:

https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.js#L5270

It could happen, that some variables interpreted different on newest Firefox in Fedora.
I add debug output at this place. With the link:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz

I see in console:  
`JSROOT.gStyle = {"Tooltip":2,"ContextMenu":true,"Zooming":true,"MoveResize":true,"DragAndDrop":true,"ToolBar":true,"OptimizeDraw":1,"DefaultCol":1,"AutoStat":true,"OptStat":1111,"OptFit":0,"FrameNDC":{"fX1NDC":0.07,"fY1NDC":0.12,"fX2NDC":0.95,"fY2NDC":0.88},"StatNDC":{"fX1NDC":0.78,"fY1NDC":0.75,"fX2NDC":0.98,"fY2NDC":0.91},"StatText":{"fTextAngle":0,"fTextSize":9,"fTextAlign":12,"fTextColor":1,"fTextFont":42},"StatFill":{"fFillColor":0,"fFillStyle":1001},"TimeOffset":788918400000,"StatFormat":"6.4g","FitFormat":"5.4g","Palette":57,"MathJax":0,"ProgressBox":true,"Embed3DinSVG":2,"NoWebGL":false}`
`touches=false zooming=true context=true ismain=true`. 

Can you check them?

**Comment by mvala** [comment]
```
"Set JSROOT.source_dir to http://jsroot.gsi.de/dev/, dev 17/03/2016" JSRootCore.min.js:1:2684
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. dev
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.v3.min.js:3:10389
zaxis path 118 JSRootPainter.min.js:1:76817
xaxis path 409 JSRootPainter.min.js:1:76817
yaxis path 451 JSRootPainter.min.js:1:76817
zaxis path 118 JSRootPainter.min.js:1:76817
JSROOT.gStyle = {"Tooltip":2,"ContextMenu":true,"Zooming":true,"MoveResize":true,"DragAndDrop":true,"ToolBar":true,"OptimizeDraw":1,"DefaultCol":1,"AutoStat":true,"OptStat":1111,"OptFit":0,"FrameNDC":{"fX1NDC":0.07,"fY1NDC":0.12,"fX2NDC":0.95,"fY2NDC":0.88},"StatNDC":{"fX1NDC":0.78,"fY1NDC":0.75,"fX2NDC":0.98,"fY2NDC":0.91},"StatText":{"fTextAngle":0,"fTextSize":9,"fTextAlign":12,"fTextColor":1,"fTextFont":42},"StatFill":{"fFillColor":0,"fFillStyle":1001},"TimeOffset":788918400000,"StatFormat":"6.4g","FitFormat":"5.4g","Palette":57,"MathJax":0,"ProgressBox":true,"Embed3DinSVG":2,"NoWebGL":false} JSRootPainter.min.js:1:109264
touches=true zooming=true context=true ismain=true
```

**Comment by linev** [comment]
AAAAA!

touches=true 

This is main problem. But why?

**Comment by linev** [comment]
Detection of touch device is not working as expected.
I will investigate.

**Comment by mvala** [comment]
i see, thanks for such support

**Comment by linev** [comment]
Once it should happened :(

I was using either mouse or touch events, but not both of them.
But there are devices, which could support both.
Now mouse events should be handled always, touch are optional.
Please try once again:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=colz

**Comment by mvala** [comment]
it is working !!!!

**Comment by linev** [comment]
Grate and thanks for help debugging this
