### ISSUE TITLE
jsroot gui doesn't want to load my root file

### ISSUE THREAD

**Issue by mvala** [mvala/jsroot-example#5]
@linev 
in commit 612bf0b707dc6bdfb8020d1b948a7c001f0f4acd i try to add gui. It works for http://jsroot.gsi.de/files/hsimple.root but it is not working for my file. Can you check, please?

**Comment by linev** [comment]
Your are hitting CORS restriction of the browsers.
It is described here:

https://github.com/linev/jsroot/blob/master/docs/JSROOT.md#reading-root-files-from-other-servers

Just configure your server correctly.

**Comment by mvala** [comment]
Thanks. it fixed the problem. But now i am getting 
`R__unzip: mismatch between unpacked size and keys info 16777215 - 145834070`

**Comment by mvala** [comment]
When i click on one of list

**Comment by linev** [comment]
This could be much complex issue.
It looks like you try to read and unpack object which is much bigger than 16 MB.
This not yet supported in JSROOT.

But does it make sense at all?
To my experience browser can only work with about 100MB of data in JavaScript.
If I just try to download and unpack such object, it most probably hangs.

I download your file - you have two TList objects, both with many large objects inside.
Could you write them separately with sub-directory structure and individual TKey object?

Anyway, I will check if I could help.

**Comment by mvala** [comment]
i see, this file is that big from analysis. In my case i would only need info about file and what objects are inside. I don't need browse file, i will just trigger some additional analysis with these objects and send them to cluster.

**Comment by linev** [comment]
But you store all your objects in TList and write them into the TFile.
To be able browse them (see that inside TList), I need first download complete object, unzip it (now it fails) and than reconstruct ALL objects in browser memory. Most probably, it will not work this way.

I just want to check how smaller TList objects are working (never tried before)

**Comment by mvala** [comment]
I see.

**Comment by mvala** [comment]
I think i can produce json locally and then show info i need. so we can close it, because TList has to always download itself.

**Comment by linev** [comment]
If you have server application anyway, it much easier produce necessary summary information there.
But TList I will try - I had long time ago example, but did not test it for a while.

**Comment by linev** [comment]
Should work now.

http://jsroot.gsi.de/dev/?file=../files/a.root&item=RsnOut_tpc3s_extra;1/hEventStat

I knew this from beginning, that big (>16MB) zipped buffers are not supported.
But never put an effort to implement this, while typical objects much smaller.

Even if works, I recommend to use different approach - put smaller objects or use Node.js server functionality
